export const SIDEBAR_OPEN = 'SIDEBAR_OPEN'
export const INPUT_MESSAGE_CHANGE = 'INPUT_MESSAGE_CHANGE'
export const CLEAR_MESSAGE_INPUT = 'CLEAR_MESSAGE_INPUT'
export const POST_CHAT_MESSAGE = 'POST_CHAT_MESSAGE'
export const ADD_CHANNEL = 'ADD_CHANNEL'
export const CHANGE_CHANNEL = 'CHANGE_CHANNEL'




